# install_roles.yml

# From galaxy
- src: geerlingguy.apache
- src: geerlingguy.composer
- src: geerlingguy.mysql
- src: geerlingguy.nodejs
- src: geerlingguy.php
- src: geerlingguy.php-xdebug
- src: pludoni.wkthmltox